### ISSUE TITLE
Update for VS2019

### ISSUE THREAD

**Issue by dragokas** [cocus/openmsvbvbm#4]
Hi,
thanks for this amazing project!

Can you please update it to be able to build in the latest VS2019 without errors?

Thank you.

**Comment by cocus** [comment]
Hi, can you explain which issues are you facing? If I'm not mistaken, I'm running the latest VS2019 and I can build this code

Thanks

**Comment by dragokas** [comment]
Ahh, sorry, my fault.
VS by default opened the project in x64 mode and I didn't notice that.
